<?php



return [
    'logo_path'=> "/vendor/nhelper/assets/images/logo.png",
    'favicon_path'=> "/vendor/nhelper/assets/images/logo.png",
    'importer'=>"/vendor/nhelper/img/importer.png",
    'inscriptionSociete'=>"/vendor/nhelper/img/inscriptionSociete.png",
    'Articles'=>"/vendor/nhelper/img/Articles.xlsx",
    'importation'=>"/vendor/nhelper/img/importation.png",
    'creationP'=>"/vendor/nhelper/img/creationP.png",
    'tablearticle'=>"/vendor/nhelper/img/tablearticle.png",
    'modif'=>"/vendor/nhelper/img/modif.png",
    'info'=>"/vendor/nhelper/img/info.png",
    'supprim'=>"/vendor/nhelper/img/supprim.png",
    'Cat'=>"/vendor/nhelper/img/Cat.png",
    'actif'=>"/vendor/nhelper/img/actif.png",
    'AjoutCat'=>"/vendor/nhelper/img/AjoutCat.png",
    'Rcat'=>"/vendor/nhelper/img/Rcat.png",
    'Cajout'=>"/vendor/nhelper/img/Cajout.png",
    'listCli'=>"/vendor/nhelper/img/listCli.png",
    'DOC1'=>"/vendor/nhelper/img/DOC1.png",
    'Apercu'=>"/vendor/nhelper/img/Apercu.png",
    'Modif1'=>"/vendor/nhelper/img/Modif1.png",
    'valider'=>"/vendor/nhelper/img/valider.png",
    'proforma'=>"/vendor/nhelper/img/proforma.png",
    'Facture'=>"/vendor/nhelper/img/Facture.png",
    'Certification'=>"/vendor/nhelper/img/Certification.png",
    'newclient'=>"/vendor/nhelper/img/newclient.png",
    'fact'=>"/vendor/nhelper/img/fact.png",
    'fact2'=>"/vendor/nhelper/img/fact2.png",
    'FACLIST'=>"/vendor/nhelper/img/FACLIST.png",
    'Preview'=>"/vendor/nhelper/img/Preview.png",
    'M1'=>"/vendor/nhelper/img/M1.png",
    'valide1'=>"/vendor/nhelper/img/valide1.png",
    'certifier'=>"/vendor/nhelper/img/certifier.png",
    'proforma1'=>"/vendor/nhelper/img/proforma1.png",
    'facture1'=>"/vendor/nhelper/img/facture1.png",
    'A_R'=>"/vendor/nhelper/img/A_R.png",
    'supprimer'=>"/vendor/nhelper/img/supprimer.png",
    'Modif1'=>"/vendor/nhelper/img/Modif1.png",
    'certifier'=>"/vendor/nhelper/img/certifier.png",
    'Generaux'=>"/vendor/nhelper/img/Generaux.png",
    'docFactu'=>"/vendor/nhelper/img/docFactu.png",
    'Amembre'=>"/vendor/nhelper/img/Amembre.png",
    'refere'=>"/vendor/nhelper/img/refere.png",


];
